# Generated by Django 4.2.1 on 2023-10-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interviewed', 'Interviewed'), ('Reference Check', 'Reference Check'), ('Offer Extended', 'Offer Extended'), ('Offer Accepted', 'Offer Accepted'), ('Offer Declined', 'Offer Declined'), ('Not Selected', 'Not Selected'), ('On Hold', 'On Hold'), ('Withdrawn', 'Withdrawn')], default='Received', max_length=255, null=True),
        ),
    ]
