# Generated by Django 4.2.1 on 2023-10-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_remote', models.BooleanField(default=False)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('5+', '5+')], max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
