# Generated by Django 4.2.1 on 2023-10-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
