# Generated by Django 4.2.1 on 2023-10-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_job_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=255)),
                ('date_of_birth1', models.DateField()),
                ('state1', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=255)),
                ('gender1', models.CharField(max_length=10)),
                ('location1', models.CharField(max_length=255)),
                ('profile_image1', models.ImageField(upload_to='profile_images')),
                ('resume_pdf1', models.FileField(upload_to='resume_file')),
                ('status1', models.CharField(choices=[('Received', 'Received'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interviewed', 'Interviewed'), ('Reference Check', 'Reference Check'), ('Offer Extended', 'Offer Extended'), ('Offer Accepted', 'Offer Accepted'), ('Offer Declined', 'Offer Declined'), ('Not Selected', 'Not Selected'), ('On Hold', 'On Hold'), ('Withdrawn', 'Withdrawn')], default='Received', max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.job')),
            ],
        ),
    ]
